### ISSUE TITLE
Function-like mockup interface

### ISSUE THREAD

**Issue by xxthunder** [avengineers/hammocking#8]
As a SW developer I would like to have a nice and neat mockup interface to make my tests readable.

E.g., mimicc creates nice mockups:
* https://mimicc.dev/mimicc-resource/userguidehtml/#mock-api-reference
* https://github.com/avengineers/hammock/tree/feature/mimicc-playground/resources/mini_c (main.c and mock-main.h)
  * created with `mimicc -c -o mock_main.o main.h -Wall --hout=mock-main.h -v`

Acceptance criteria:
* Mockup expect() interface is available to check that function foo() is called at least once, e.g., `HAM_FUNC(foo).expect()` 👍 
* Mockup expect() interface is available to check that function foo(var a, var b) is called at least once with expected parameters, e.g., `HAM_FUNC(foo).expect(someValueForA, someValueForB)` 👍 
* Mockup returns() interface is available, e.g., `HAM_FUNC(foo).returns(someReturnValueOfFoo)` 👍 

Issue is solved by creating gmock mockups. See https://google.github.io/googletest/reference/mocking.html

**Comment by theHolgi** [comment]
Thinking loud:
How to handle function parameters?
With template classes, we need to explicitly implement a template for functions with 0,1,2,3, ... parameters, with mostly identical content.
With variable arguments, one might get the flexibility to cover everything with one class, but can only check at runtime for correct usage and has no IDE hinting.
So it sounds like a case for code generation?

**Comment by xxthunder** [comment]
GMock is the solution for now.
